### ISSUE TITLE
Dynamic Starter Kit

### ISSUE THREAD

**Issue by trruckerfling** [filecoin-project/fil-b#13]
can you pls help add lighthouse's storage with FVM here? https://github.com/dynamic-labs/hackathon-starter-kit @rk-rishikesh

**Comment by rk-rishikesh** [comment]
Created the PR here : https://github.com/dynamic-labs/hackathon-starter-kit/pull/23/commits

**Comment by rk-rishikesh** [comment]
PR Merged : https://github.com/dynamic-labs/hackathon-starter-kit
