### ISSUE TITLE
 Build FILB Devrel Tracker

### ISSUE THREAD

**Issue by trruckerfling** [filecoin-project/fil-b#14]
A builder database of key builders and projects we want to nurture closely for either open source contributions or teams to send to accelerators

**Comment by longfeiWan9** [comment]
FILB Dev tracker is implemented in Airtable https://airtable.com/appHlddLwqQ7vZwOo/tblqpShsnyEpbgS3E/viw7RZUMCK29dD5zG?blocks=hide
