### ISSUE TITLE
Smart Contract Verification

### ISSUE THREAD

**Issue by xBalbinus** [filecoin-project/fil-b#3]
**Description:**

Verifying smart contracts at the moment is a pain for users. There are unknown errors that are 'hard to fix'

- **Breakage:**
  [Provide a detailed description of the issue here, including any links to available evidence or original user posts as much as possible]

https://filecoinproject.slack.com/archives/CRK2LKYHW/p1720593649171469?thread_ts=1720447325.817329&cid=CRK2LKYHW

- **Component related to:**
  [Specify the feature or component related to the issue]

FILFOX contract verification API

- **Impact on devs:**
  [Explain why this issue is important and how it affects development]

Cannot verify smart contracts

- **Ideal solution:**
  [Describe the desired solution or the happy path]

**Additional Context:**

**Comment by xBalbinus** [comment]
Idea: https://docs.filecoin.io/smart-contracts/developing-contracts/verify-a-contract We should probably update this page with the latest of FILFOX et al.'s APIs for verification.

**Comment by longfeiWan9** [comment]
@xBalbinus What are the next steps or proposed action items for this pain point?

**Comment by trruckerfling** [comment]
Bump please @xBalbinus can we close this off?

**Comment by xBalbinus** [comment]
https://github.com/filecoin-project/filecoin-docs/pull/2313

**Comment by trruckerfling** [comment]
It's inconsistent but this is due to a larger filfox issue. Closing this issue now to link to a new one around the filfox issue
