### ISSUE TITLE
Axelar unreliability seems to be a result of lotus eth rpc unreliability:

### ISSUE THREAD

**Issue by xBalbinus** [filecoin-project/fil-b#46]
**Description:**
Axelar unreliability seems to be a result of lotus eth rpc unreliability: https://filecoinproject.slack.com/archives/C04FFBJDSV8/p1723127346311159?thread_ts=1723073923.251869&amp;cid=C04FFBJDSV8

They are getting tx not found errors

**Source:**
https://filecoinproject.slack.com/archives/C0745JU645A/p1723128188753849

**Comment by trruckerfling** [comment]
Resolved with eth addressing improvements to ETH RPC API on lotus https://github.com/filecoin-project/lotus/pull/12261.
