### ISSUE TITLE
withdraw/send FIL between f1 and 0x

### ISSUE THREAD

**Issue by longfeiWan9** [filecoin-project/fil-b#47]
**What is the issue?**
The user is asking for an easy way to send FIL from f1 to 0x address without using the burner wallet, and to make it easier to onboard FIL to MetaMask. 

**What are the proposed solutions?**
Actually, FilForward by Glif support sending tokens from f1 -> 0x (requires filecoin SDK), then 0x -> f1 (goes through FilForward). FilForward can serve as an underlayer protocol to achieve 0x -> f1, just need more wallet UI to support it (Glif is one of them.)
- We need to build a good Filecoin wallet using FIL-snap, https://filsnap.fission.app/ is too simple and lacks of features.
- Who is maintaining [FilForward](https://github.com/FILCAT/FilForwarder)? Is it going to be audit and use as an official infra/tools to send FIL from 0x to f1? 

**Source:**
https://x.com/ChillMillEd/status/1815528743861129726

**Comment by trruckerfling** [comment]
Discussed. Next step to look into productionizing FilSnap. Another existing solution is glif wallet.

**Comment by smagdali** [comment]
[This devgrant](https://github.com/filecoin-project/devgrants/issues/1762) has been approved.
