### ISSUE TITLE
Null round error on calibration with hardhat

### ISSUE THREAD

**Issue by xBalbinus** [filecoin-project/fil-b#62]
**Description:**
- When trying to [deploy IPC subnet](https://github.com/consensus-shipyard/ipc/blob/main/contracts/ops/deploy.sh), anchored to calibration net, getting error `requested epoch was a null round`. 
- IPC team helped Identify issue as the hardhat http provider that doesn't recognise null blocks since null blocks are unique to Filecoin 

**Source:**
https://filecoinproject.slack.com/archives/C017HM9BJ8Z/p1722416473044169?thread_ts=1722416473.044169&cid=C017HM9BJ8Z

**Comment by trruckerfling** [comment]
There is a fix within [IPC's deployment scripts](https://filecoinproject.slack.com/archives/C017HM9BJ8Z/p1723559498303519?thread_ts=1722416473.044169&cid=C017HM9BJ8Z), we need to look into it. TBD what the solution is @xBalbinus can you look into this pls?

**Comment by xBalbinus** [comment]
https://filecoinproject.slack.com/archives/C01D42NNLMS/p1723648716876729?thread_ts=1723128284.292969&cid=C01D42NNLMS

This was previously forwarded to folks at FF, and subsequently resolved.
