### ISSUE TITLE
storage onramps docs article is outdated

### ISSUE THREAD

**Issue by xBalbinus** [filecoin-project/fil-b#65]
**Description:**
https://docs.filecoin.io/basics/what-is-filecoin/storage-market#storage-on-ramps flagging that storage onramps docs article is outdated. With the new wave of onramps - akave, storacha, curio replacing boost etc. - it's worth updating this page. we refer to it quite often when explaining storage onramps

**Source:**
https://filecoinproject.slack.com/archives/CFP9A2T7W/p1725997230919679?thread_ts=1725997230.919679&cid=CFP9A2T7W

**Comment by trruckerfling** [comment]
Resolved https://docs.filecoin.io/basics/what-is-filecoin/storage-market#storage-on-ramps looks complete
