### ISSUE TITLE
Issue Verifying Contracts on Filfox: Dependency Library Bytecode Mismatch

### ISSUE THREAD

**Issue by xBalbinus** [filecoin-project/fil-b#71]
**Description:**
Anyone had luck verifying contracts on filfox?  I can upload my project files and the compiler seems to be matching the bytcode but instead of resolving to the main bytecode filfox thinks I’m trying to compile to the bytecode of one of the dependency libraries.  I’m not seeing any options for “which contract do you want to compile.”

**Source:**
https://filecoinproject.slack.com/archives/CRK2LKYHW/p1728504279175599?thread_ts=1728504279.175599&cid=CRK2LKYHW

**Comment by trruckerfling** [comment]
Related to #79 suggestion. Closing this issue but good to note it as proof of builder issues and the need to reroute from filfox to another explorer
