### ISSUE TITLE
Request for FEVM Pyth/Tellor Starter Kit to Fetch FIL/USD Exchange Rate

### ISSUE THREAD

**Issue by xBalbinus** [filecoin-project/fil-b#78]
**Description:**
Hey @longfeiwang.88 Please can you link me to a FEVM  Pyth/Tellor starter kit/example to see how to use those to fetch the FIL  USD exchange rate ? I have something working but wanna ensure it's the right way to do things.

**Source:**
https://filecoinproject.slack.com/archives/C0745JU645A/p1733734142103419

**Comment by trruckerfling** [comment]
think the slack URL was wrong - clicking doesn't find post. But iirc this is the [OP](https://filecoinproject.slack.com/archives/C0745JU645A/p1733734142103419) and is now resolved. Closing.

**Comment by xBalbinus** [comment]
Should keep tracking this on FIL Frame, close here. Not fully done yet
(iirc, contributors are wip).
